---
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["master"]
    types: ["opened", "synchronize", "reopened"]

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  simple-checks:
    uses: drag0n141/containers/.github/workflows/simple-checks.yaml@35c912bd9d4d83c1b12d4d066dd87541d6f46176 # master

  get-changed-images:
    uses: drag0n141/containers/.github/workflows/get-changed-images.yaml@35c912bd9d4d83c1b12d4d066dd87541d6f46176 # master

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: drag0n141/containers/.github/workflows/build-images.yaml@35c912bd9d4d83c1b12d4d066dd87541d6f46176 # master
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: false
      sendNotifications: false
