---
name: Release on Merge

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  push:
    branches: ["master"]
    paths:
      - "apps/**"
      - ".github/scripts/templates/**"
      - "!apps/**/metadata.json"
      - "!apps/**/metadata.yaml"
      - "!apps/**/README.md"

jobs:
  simple-checks:
    uses: drag0n141/containers/.github/workflows/simple-checks.yaml@master

  get-changed-images:
    needs: ["simple-checks"]
    uses: drag0n141/containers/.github/workflows/get-changed-images.yaml@master

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: drag0n141/containers/.github/workflows/build-images.yaml@master
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    if: ${{ always() && needs.build-images.result != 'failure' }}
    uses: ./.github/workflows/render-readme.yaml
    secrets: inherit
